version: '3.8'
services:
  frontend:
    build:
      dockerfile: docker/Dockerfile.frontend
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - primary-backend

  primary-backend:
    build:
      dockerfile: docker/Dockerfile.backend
      context: .
    ports:
      - "5000:5000"
    depends_on:
       db:
        condition: service_healthy

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:3.7.1
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/kafka
      - ./kafka-entrypoint.sh:/kafka-entrypoint.sh
    command: 
      - /bin/bash
      - /kafka-entrypoint.sh

  processor:
    build:
      dockerfile: docker/Dockerfile.processor
      context: .
    depends_on:
      - kafka
      - db

  worker:
    build:
      dockerfile: docker/Dockerfile.worker
      context: .
    depends_on:
      - kafka
      - db
    
  hooks:
    build:
      dockerfile: docker/Dockerfile.hooks
      context: .
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
  

volumes:
  postgres-data:
  kafka-data:
