FROM node:20-alpine

WORKDIR /worker

COPY worker/package.json .
COPY worker/package-lock.json .

RUN npm install

ENV DATABASE_URL="postgresql://postgres:mysecretpassword@db:5432/postgres"

COPY worker .

RUN npm run prisma:generate

CMD ["npm","run","start"]