FROM node:20-alpine
WORKDIR /backend

COPY backend/package.json .
COPY backend/package-lock.json .

RUN npm install

ENV DATABASE_URL="postgresql://postgres:mysecretpassword@db:5432/postgres"

COPY backend .

RUN npm run prisma:generate

EXPOSE 3001 

CMD ["npm","run","start"]